// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: command_account.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createAccount = `-- name: CreateAccount :execresult
INSERT INTO account (id, name, email, password, status)
VALUES (?, ?, ?, ?, ?)
`

type CreateAccountParams struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Status   int    `json:"status"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAccount,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Status,
	)
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT id, name, email, password, status, created_at
FROM account
WHERE email = ? LIMIT 1
`

func (q *Queries) GetAccountByEmail(ctx context.Context, email string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByEmail, email)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
