// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (sql.Result, error)
	GetAccountByEmail(ctx context.Context, email string) (Account, error)
}

var _ Querier = (*Queries)(nil)
